### ISSUE TITLE
Complains about trailing punctuation even if title ends with abbreviation

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#107]
A commit message ending in an abbreviation produces an error even if the trailing punctuation should be considered part of the abbreviation and not punctuation ending the title:
```
T3 Title has trailing punctuation (.): "Implement scalar division for modules etc."
```

**Comment by drasmuss** [comment]
Seems like an issue to raise with [gitlint](https://github.com/jorisroovers/gitlint) if you think the behaviour should be changed; all we're doing in nengo-bones is calling that tool.

**Comment by jgosmann** [comment]
Opened upstream issue jorisroovers/gitlint#136.
