### ISSUE TITLE
Recommend to use PyPI API tokens instead of username + password

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#108]
The [documentation currently recommends setting the PyPI username and providing the password in the TravisCI settings](https://www.nengo.ai/nengo-bones/examples/configuration.html#Automatic-deployment). It should rather recommend using an [API access token] which can be/is restricted to package uploads, can be restricted to a single PyPI project, and individually revoked.

The `pypi_user` option could be phased out as it will always be `__token__` for access tokens.

**Comment by tbekolay** [comment]
These tokens didn't exist when we were originally doing releases, hence why it's not part of the process. It would be good to switch to them for sure. However, part of the use of `pypi_user` is to determine whether or not the project is set up for deployment, so we'll need some other mechanism for this if we switch to API tokens.

**Comment by arvoelke** [comment]
> ... to determine whether or not the project is set up for deployment, so we'll need some other mechanism for this ...

Could this be achieved by checking for either the existence of `- template: deploy` under `ci_scripts` or for the existence of `manifest_in: {}`? I noticed the deploy script fails if either is missing from `.nengobones.yml`. In the former case you get the error:
```
/home/travis/.travis/functions: line 109: .ci/deploy.sh: No such file or directory
```
and in the latter case you get the error:
```
no MANIFEST.in found; you can run 'check-manifest -c' to create one
suggested MANIFEST.in rules:
  include *.rst
  include *.yml
  recursive-include docs *.ipynb
COMMAND 'check-manifest' FAILED
```
