### ISSUE TITLE
Deployment to PyPI fails

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#125]
For NengoSPA the deployment to PyPI fails for reasons not clear to me.

[In the log](https://travis-ci.com/github/nengo/nengo-spa/jobs/427160737#L695) it says:
```
Skipping a deployment with the pypi provider because a custom condition was not met
Skipping a deployment with the pypi provider because this is not a tagged commit
```
But as far as I can tell the condition is that the tag starts with `v` and a number (which it does for `v1.1.1`) and the commit is definitely tagged, Travis CI even says so on top of the page.

(I did the deployment manually then.)

**Comment by tbekolay** [comment]
That's quite strange, it definitely looks like it should have worked. The only thing that comes to mind is that we migrated from travis-ci.org to travis-ci.com recently, it could be related to that? I'm not sure if NengoSPA was on .org before or not though.

**Comment by jgosmann** [comment]
It was on .org before ... but not sure how that would impact the deployment in this way.

**Comment by jgosmann** [comment]
It's not working reproducibly: https://travis-ci.com/github/nengo/nengo-spa/jobs/440261234

**Comment by drasmuss** [comment]
It's been working correctly for other repos, so I would guess that it's something in the `nengo-spa` settings (the `PYPI_TOKEN` being set incorrectly would be the most likely culprit). For example, I notice that you have three different `PYPI_TOKEN` variables in your settings, and they're restricted to particular branches. Most likely that variable is not available when you're doing the tagged build.

**Comment by drasmuss** [comment]
(Note that the error is here https://travis-ci.com/github/nengo/nengo-spa/jobs/440261234#L701, the message about one of the deployment builds being skipped is expected, since there are two different deployment builds and only one of them should trigger in any given situation).

**Comment by jgosmann** [comment]
I'll look into the PyPI token, but is there any way to get a more useful error message (i.e. no false statement of the commit not being tagged and make the actual error message about the option stand out more)?

**Comment by drasmuss** [comment]
That's all TravisCI output, but you could try opening an issue with them asking them to change it.

**Comment by jgosmann** [comment]
The issue was likely that I had the token only configured for the `master` branch, but the deployment happens from the build for the tag. The tokens should be configured correctly now, but might take a while until the next release. So I'll close the issue for now.
