### ISSUE TITLE
Have remote script immediately fail if it fails to install and run Miniconda

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo-bones#129]
Currently, if the remote script fails to properly install and run Miniconda, the script defaults to using the system python and then installs the required python packages to the user's system local python installation. It would be great if instead the script just exits with a fail immediately on detection of a failed install / run of Miniconda.

**Comment by xchoo** [comment]
In theory, this should be as straightfoward as adding a check (maybe `which conda`?) before this line:
https://github.com/nengo/nengo-bones/blob/05546feb9b814e3d375ed95d03971ac98e45580b/nengo_bones/templates/remote.sh.template#L100

**Comment by drasmuss** [comment]
This was fixed as a side-effect of #130
