### ISSUE TITLE
Change Travis CI dist to xenial or make it configurable

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#27]
For Nengo SPA I want to run the test also with Python 3.7 which requires to [set `dist: xenial` in .travil.yml](https://docs.travis-ci.com/user/languages/python/#python-37-and-higher). This is currently not possible with nengo-bones.

**Comment by drasmuss** [comment]
Yep it is possible to set that in nengo bones.  As mentioned [here](https://www.nengo.ai/nengo-bones/examples/configuration.html#Jobs), you can add arbitrary entries to a job section, which will be added directly into the `.travis.yml` file.  So you can just set `dist: xenial` in your `.nengobones.yml` job specification, and that will be passed on to Travis.  You can see an example here https://github.com/nengo/nengo/pull/1524/commits/ff98877b3caecb861350f364d2115a98ecd9828f.

**Comment by jgosmann** [comment]
It does not seem to work globally, but needs to be done for each job?

**Comment by drasmuss** [comment]
Yes every setting in the `jobs` section only affects that job, they do not have any global side-effects.

**Comment by jgosmann** [comment]
I was referring to setting it outside of the jobs section like the python version.

**Comment by drasmuss** [comment]
No that's right, that won't work outside the jobs section.  The "passing arbitrary options on to .travis.yml" is only enabled within the job configurations, in all other cases the options available are only those described in the nengo-bones documentation.

**Comment by drasmuss** [comment]
Closing this out as the `dist: xenial` option in the job section is available and is the recommended way to change the distribution.  But feel free to reopen if there is anything else you want to discuss.
