### ISSUE TITLE
Speed up pylint using multiple cores

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-bones#29]
Pylint accepts a `-j` flag, which you can set as `-j 0` to use all available CPUs. It speeds up execution on my machine quite a bit; checking the Nengo core source went from 37 seconds wall time to 12 seconds.

There might be reasons not to enable this flag though, hence why I'm making an issue about it rather than just doing it in an open PR.

**Comment by drasmuss** [comment]
Done in https://github.com/nengo/nengo-bones/pull/49
