### ISSUE TITLE
Using setup.cfg to configure pylint decreases quality of life when running pylint from the command line

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#31]
`pylint` looks only for `.pylintrc` by default. Because nengo-bones expects the pylint config into the `setup.cfg` more typing is required when manually running `pylint` from the command line, i.e.
```bash
pylint nengo_spa --rcfile=setup.cfg
```
instead of just
```bash
pylint nengo_spa
```

Can the config be moved back to setup.cfg?

**Comment by tbekolay** [comment]
What I usually do is run `static.sh script` as I usually want to do all the static checks. If I'm modify templates, then I'll do

```bash
generate-bones --output-dir .ci ci-scripts && .ci/static.sh script
```

**Comment by drasmuss** [comment]
The idea behind `setup.cfg` is to prevent the proliferation of configuration files in the top-level directory, which I believe is worth a little bit more typing in this instance.

**Comment by jgosmann** [comment]
> What I usually do is run `static.sh script` as I usually want to do all the static checks.

I suppose I can live with that.
