### ISSUE TITLE
Cannot find nengo-bones on Travis CI anymore

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#40]
See for example this build: https://travis-ci.org/nengo/nengo-spa/jobs/539885439
Even though nengo-bones 0.2.1 gets installed, the generate-bones command is not found. It is not clear to my why at the moment. It was working previously (with an install from master), but stopped working after I made changes to unrelated Jupyter notebooks. Then I changed the config to install from pip without any change.

**Comment by jgosmann** [comment]
I probably figured it out: I was still using an older version locally. It might be a good idea to ensure that the scripts that are generated locally and checked in use the same nengo-bones version on the CI system that was used to generate them. Those scripts should not break just because a newer version was released.

**Comment by jgosmann** [comment]
Or maybe I did not figure it out. [This job](https://travis-ci.org/nengo/nengo-spa/jobs/539889921) fails with the same error and seems to call the correct command now (bones-generate).

**Comment by tbekolay** [comment]
The failure is because the TravisCI job is using Python 2.7 so it still installs an older version of nengo-bones, a version before we set `python_requires>=3.5`.

**Comment by jgosmann** [comment]
So is there no way to still support Python 2.7 and 3.4 when using nengo-bones?

**Comment by drasmuss** [comment]
That's correct.  We're dropping support for Python<3.5 across the nengo ecosystem, but we haven't gotten around to upgrading all the repos yet.  It'll probably happen at the same time as we roll out nengo-bones to more repos.

**Comment by drasmuss** [comment]
> Those scripts should not break just because a newer version was released.

This is an intentional part of nengo-bones' design.  The idea is to enforce a common standard across the nengo ecosystem, so we want an explicit error whenever a repo is not up to date.  That being said, the error should be the informative one provided by `bones-check`, not the syntax error you were getting (due to the name changing from `generate-bones` to `bones-generate`). But that's due to the fact that nengo-bones is still in the alpha phase where there aren't really any guarantees of API stability, that will settle down once we due a 1.0 release.

**Comment by jgosmann** [comment]
> We're dropping support for Python<3.5 across the nengo ecosystem

Not sure if I want to do this for Nengo SPA already. Nengo 3 hasn't been released yet and Nengo SPA is still supporting Nengo 2.7/2.8 which also supports Python 2.7.

I think ideally the Python version to run the test infrastructure should be independent of the Python version under which the tests are run, but I suppose that might be non-trivial.

> > Those scripts should not break just because a newer version was released.
> 
> This is an intentional part of nengo-bones' design. The idea is to enforce a common standard across the nengo ecosystem, so we want an explicit error whenever a repo is not up to date.

While some sort of “notification” about a new nengo-bones release would be nice, I don't think that it is a good idea in this form as it means that the CI build can randomly break due to changes outside of the respective repository (which would be ok if it is due to a hard dependency, i.e. Numpy making a backwards compatible change, but the testing infrastructure should not randomly break). And while the build is broken in this way, the CI feedback on all PRs would be pretty useless on all PRs until nengo-bones is updated in that project (which might require code changes itself, for example to adhere to new static checks).

**Comment by drasmuss** [comment]
> Not sure if I want to do this for Nengo SPA already. Nengo 3 hasn't been released yet and Nengo SPA is still supporting Nengo 2.7/2.8 which also supports Python 2.7.

Nengo 2.7/2.8 both support Python>=3.5, so dropping support for old Python versions is not inconsistent with supporting older Nengo versions.  That being said, you are of course free not to worry about this now if you don't want to, and we can take care of updating `nengo-spa` when we have the chance.

> While some sort of “notification” about a new nengo-bones release would be nice, I don't think that it is a good idea in this form

We'll just have to agree to disagree on that one.  As above, you are definitely free to not worry about nengo-bones at all, and we will take care of applying it to nengo-spa when the time comes.

**Comment by jgosmann** [comment]
Regarding Python 2.7 I just want to think this through before dropping the support and it would mean for me that integrating nengo-bones would be a new minor release instead of a patch release (which I had planned before).

> As above, you are definitely free to not worry about nengo-bones at all, and we will take care of applying and maintaining it in nengo-spa when the time comes.

The problem isn't maintaining nengo-bones within Nengo SPA, but that a new nengo-bones release will affect *all* maintenance work (as in merging, reviewing PRs, etc). It basically requires to update nengo-bones first before any other PR can be processed, even though that might not have the highest priority.

Also, nengo-bones releases are announced in the forum which should already keep every maintainer of a Nengo project informed when it is time to update nengo-bones in their projects.

**Comment by drasmuss** [comment]
> It basically requires to update nengo-bones first before any other PR can be processed

Yes, that is intentional, as we want to make sure that the CI that validates the work is up-to-date before doing any further work.  If this proves to be onerous in the future we might consider changing it, but for now I'd say that is unlikely to change.

**Comment by jgosmann** [comment]
I still think that is the wrong approach (and even goes against the principles of the Scrum process which you adopted afaik), but I suppose that the advantages of adopting nengo-bones for Nengo SPA would outweight the disadvantages introduced by this issue.

Regarding the initial problem described in this issue: I think this might already be fixed for future version updates (i.e. it only happened for the update to 0.2)? In that case feel free to close the issue.
