### ISSUE TITLE
Cannot change Sphinx theme

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#43]
The Sphinx theme cannot be changed because `sphinx_options` will be inserted in front of the `html_theme` option in the Sphinx configuration. This will block adaption of nengo-bones in Nengo SPA as there are still other issues in `nengo_sphinx_theme` to be resolved (nengo/nengo-sphinx-theme#15).

**Comment by drasmuss** [comment]
This is one of the options that is intentionally standardized in nengo-bones, we want all nengo ecosystem projects to be using the same theme.  There'll be an update to nengo-sphinx-theme soon, but we'll track those issues in that repo.
