### ISSUE TITLE
Handle pytest options more generically

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-bones#54]
Currently we have a bunch of possible pytest options, and it takes a new release of Nengo Bones every time we have a new one. It would be nice if we could do this in a more generic way, kind of like we do with extra arguments passed in the `travis_yml` section. It's a little bit more complicated because we're going from `yaml` to `ini` syntax, but it should still be doable.

**Comment by drasmuss** [comment]
Conclusion from discussion: we're not averse to doing this, but we probably wouldn't do it unless we have some motivating work in the future that was touching more pytest options.
