### ISSUE TITLE
Did you consider Cookiecutter?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-bones#6]
Just discovered nengo-bones and was wondering whether you considered [Cookiecutter](https://cookiecutter.readthedocs.io/en/latest/)? It seems to cover the same project template use case, but I'm not really familiar with it. (I believe I used it once to start some Jupyter widget project from their official template repo.)

**Comment by drasmuss** [comment]
Yeah I looked at cookiecutter a while ago but never actually used it.  Maybe I'll see if it could help when I work on expanding #5 to cover more files (beyond the TravisCI config).

**Comment by drasmuss** [comment]
Update on this, I looked into cookiecutter but it didn't seem like it'd work well for this use case (one of the main downsides being that it is difficult for downstream repos to modify the template).  So closing this out, but feel free to reopen if there's anything else to discuss.
