### ISSUE TITLE
Consider using overwritable base template variables

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-bones#63]
Working on the `nengo-fpga` custom `docs.sh.template` script I noticed that I couldn't overwrite the `{{ docs_dir }}` variable ([set here](https://github.com/nengo/nengo-bones/blob/master/nengo_bones/templates/docs.sh.template#L3)).

I did a little Googling and found [this page](https://www.titonbarua.com/posts/2014-02-07-about-variable-overriding-behavior-of-jinja2). Essentially, the parent/base script is read _after_ the child script so even if I set a variable in the child script, the parent script's definition clobbers it. This post suggests a more permissive definition of variables in parent scripts which will accept an existing (child overwritten) value:

`{% set docs_dir = docs_dir | default("../" + repo_name.split("/")[1] + "-docs") %}`
_Note, I haven't tested this and just transcribed the example in the linked post to our context_

**Comment by drasmuss** [comment]
I think you ended up implementing this in a different way such that this wasn't necessary anymore right, if I remember the discussion correctly?

**Comment by bmorcos** [comment]
This is more of a nice-to-have thing, I just work around the prepended `../` by entering another directory first. [eg:](https://github.com/nengo/nengo-fpga/blob/bones/.templates/docs.sh.template#L80),
```
        # The docs_dir is set in the base and has "../" prepended,
        # so we enter another dir first
        cd nengo-fpga-"$TRAVIS_JOB_NUMBER"
        rm -rf {{ docs_dir }}
```

I didn't test the default assignment I noted above, but if it's that simple to implement it may be worth doing just to make things easier and cleaner in the future?

**Comment by drasmuss** [comment]
Since you have a workaround and it seems kind of unlikely to come up again outside of this use case, we're thinking this probably won't get done any time soon.  Not that it wouldn't be a good thing to do, it's just probably never going to get prioritized if we're being honest.  So closing to reflect that there are no current plans to do this, but if there was some further use case we would definitely be open to adding this.
